apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-a
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Atul-Munde/argocd-example-apps
    targetRevision: master
    path: argo
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
